"""make firstname nullable

Revision ID: f3d274f370c5
Revises: 9642235db3d4
Create Date: 2026-02-24 12:47:53.524728

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f3d274f370c5"
down_revision: Union[str, Sequence[str], None] = "9642235db3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=15), nullable=True
    )
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "client", "master", name="role"),
        nullable=True,
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "client", "master", name="role"),
        nullable=False,
    )
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=15), nullable=False
    )
    # ### end Alembic commands ###
